LazyLoad=function(k){function i(c,d){var e=k.createElement(c),f;for(f in d)d.hasOwnProperty(f)&&e.setAttribute(f,d[f]);return e}function l(c){var d=n[c],e,f;d&&(e=d.callback,f=d.urls,f.shift(),h=0,f.length||(e&&e.call(d.context,d.obj),n[c]=null,s[c].length&&j(c)))}function f(){var c=navigator.userAgent;e={async:!0===k.createElement("script").async};(e.webkit=/AppleWebKit\//.test(c))||(e.ie=/MSIE/.test(c))||(e.opera=/Opera/.test(c))||(e.gecko=/Gecko\//.test(c))||(e.unknown=!0)}function j(c,d,r,h,j){var q=
function(){l(c)},m="css"===c,v=[],b,o,g,a;e||f();if(d)if(d="string"===typeof d?[d]:d.concat(),m||e.async||e.gecko||e.opera)s[c].push({urls:d,callback:r,obj:h,context:j});else{b=0;for(o=d.length;b<o;++b)s[c].push({urls:[d[b]],callback:b===o-1?r:null,obj:h,context:j})}if(!n[c]&&(a=n[c]=s[c].shift())){t||(t=k.head||k.getElementsByTagName("head")[0]);d=a.urls;b=0;for(o=d.length;b<o;++b)r=d[b],m?g=e.gecko?i("style"):i("link",{href:r,rel:"stylesheet"}):(g=i("script",{src:r}),g.async=!1),g.className="lazyload",
g.setAttribute("charset","utf-8"),e.ie&&!m?g.onreadystatechange=function(){if(/loaded|complete/.test(g.readyState)){g.onreadystatechange=null;q()}}:m&&(e.gecko||e.webkit)?e.webkit?(a.urls[b]=g.href,p()):(g.innerHTML='@import "'+r+'";',u(g)):g.onload=g.onerror=q,v.push(g);b=0;for(o=v.length;b<o;++b)t.appendChild(v[b])}}function u(c){var d;try{d=!!c.sheet.cssRules}catch(e){h+=1;200>h?setTimeout(function(){u(c)},50):d&&l("css");return}l("css")}function p(){var c=n.css,d;if(c){for(d=q.length;0<=--d;)if(q[d].href===
c.urls[0]){l("css");break}h+=1;c&&(200>h?setTimeout(p,50):l("css"))}}var e,t,n={},h=0,s={css:[],js:[]},q=k.styleSheets;return{css:function(c,d,e,f){j("css",c,d,e,f)},js:function(c,d,e,f){j("js",c,d,e,f)}}}(this.document);var WebFontConfig;if("undefined"==typeof timeline_path||"undefined"==typeof timeline_path)var timeline_path=getScriptPath("timeline-embed.js").split("js/")[0];
function getScriptPath(k){for(var i=document.getElementsByTagName("script"),l="",f=0;f<i.length;f++)i[f].src.match(k)&&(l=i[f].src);return l.split("?")[0].split("/").slice(0,-1).join("/")+"/"}
(function(){var k,i,l,f,j,u,p,e,t,n,h,s,q,c;function d(){LazyLoad.js(a.js,r)}function r(){t=!0;"en"!=a.lang?LazyLoad.js(u,w):n=!0;m()}function w(){n=!0;m()}function x(){k=!0;m()}function y(){i=!0;m()}function m(){40<h||(h++,t&&s&&k&&i&&n?q||(q=!0,VMM.debug=a.debug,v=new VMM.Timeline,v.init(a.source),o&&VMM.bindEvent(global,onTimelineHeadline,"TIMELINE_HEADLINE")):setTimeout("onloaded_check_again();",250))}var v,b,o=!1,g="";h=0;i=k=n=c=s=t=q=!1;p=timeline_path+"css/";e=timeline_path+"js/";u=timeline_path+
"js/locale/";l=!1;f=timeline_path+"css/themes/font/";j=void 0;var a={version:"1.51",debug:!1,embed:!0,width:"100%",height:"650",source:"https://docs.google.com/spreadsheet/pub?key=0Agl_Dv6iEbDadFYzRjJPUGktY0NkWXFUWkVIZDNGRHc&output=html",lang:"en",font:"default",css:p+"timeline.css?1.51",js:e+"timeline-min.js?1.51"};p=[{name:"Merriweather-NewsCycle",google:["News+Cycle:400,700:latin","Merriweather:400,700,900:latin"]},{name:"PoiretOne-Molengo",google:["Poiret+One::latin","Molengo::latin"]},{name:"Arvo-PTSans",
google:["Arvo:400,700,400italic:latin","PT+Sans:400,700,400italic:latin"]},{name:"PTSerif-PTSans",google:["PT+Sans:400,700,400italic:latin","PT+Serif:400,700,400italic:latin"]},{name:"DroidSerif-DroidSans",google:["Droid+Sans:400,700:latin","Droid+Serif:400,700,400italic:latin"]},{name:"Lekton-Molengo",google:["Lekton:400,700,400italic:latin","Molengo::latin"]},{name:"NixieOne-Ledger",google:["Nixie+One::latin","Ledger::latin"]},{name:"AbrilFatface-Average",google:["Average::latin","Abril+Fatface::latin"]},
{name:"PlayfairDisplay-Muli",google:["Playfair+Display:400,400italic:latin","Muli:300,400,300italic,400italic:latin"]},{name:"Rancho-Gudea",google:["Rancho::latin","Gudea:400,700,400italic:latin"]},{name:"Bevan-PotanoSans",google:["Bevan::latin","Pontano+Sans::latin"]},{name:"BreeSerif-OpenSans",google:["Bree+Serif::latin","Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800:latin"]},{name:"SansitaOne-Kameron",google:["Sansita+One::latin","Kameron:400,700:latin"]},{name:"Pacifico-Arimo",
google:["Pacifico::latin","Arimo:400,700,400italic,700italic:latin"]}];if("object"==typeof url_config){a.height="100%";for(b in url_config)Object.prototype.hasOwnProperty.call(url_config,b)&&(a[b]=url_config[b]);!a.source.match("docs.google.com")&&(!a.source.match("json")&&!a.source.match("storify"))&&(a.source="https://docs.google.com/spreadsheet/pub?key="+a.source+"&output=html");o=!0}else if("object"==typeof timeline_config)for(b in timeline_config)Object.prototype.hasOwnProperty.call(timeline_config,
b)&&(a[b]=timeline_config[b]);else if("object"==typeof config)for(b in config)Object.prototype.hasOwnProperty.call(config,b)&&(a[b]=config[b]);u=a.lang.match("/")?a.lang:u+a.lang+".js?1.51";a.js.match("locale")&&(a.lang=a.js.split("locale/")[1].replace(".js",""),a.js=e+"timeline-min.js?1.51");timeline_config=a;e=document.createElement("div");b=document.getElementById("timeline-embed");b.appendChild(e);e.setAttribute("id","timeline");a.width.toString().match("%")?(b.style.width=a.width,b.setAttribute("class",
"full-embed "),b.setAttribute("className","full-embed ")):(b.setAttribute("class"," sized-embed"),b.setAttribute("className"," sized-embed"),a.width-=2,b.style.width=a.width+"px");a.height.toString().match("%")?b.style.height=a.height:(a.height-=16,b.style.height=a.height+"px");e.style.position="relative";LazyLoad.css(a.css,function(){s=true;m()});if("default"==a.font)k=i=!0;else{a.font.match("/")?(j=a.font.split(".css")[0].split("/"),j=j[j.length-1],f=a.font):f=f+a.font+".css?1.51";LazyLoad.css(f,
x);for(f=0;f<p.length;f++)j==p[f].name&&(l=!0,WebFontConfig={google:{families:p[f].google}});l?LazyLoad.js("http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js",y):i=!0}try{g=parseFloat(jQuery.fn.jquery),c=g<parseFloat("1.7.1")?!1:!0}catch(z){c=!1}c?d():LazyLoad.js("http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js",d);this.onloaded_check_again=function(){m()}})();
